title: Zoo Boise Animal Identification
description: 

remote_theme: jekyll/minima

minima:
  skin: "dark"
  date_format: "%b %d, %y"
  social_links:
    
header_pages:
    - index.md
    - plaza.md
    - oz.md
    - gorongosa.md
    - africa.md
    - education.md
  
